Add typescript.md in pt-BR articles
nullstack/nullstack.github.io pull request #249
Opened 2022-10-26 22:16 UTC by murilojssilva

2022-12-12 04:39 UTC, Mortaro commented
Thanks for the PR and sorry for the delay to review it. I will review it this week （づ￣3￣）づ╭❤️～

2023-04-06 02:17 UTC, brunolm approved these changes

2023-04-06 02:22 UTC, brunolm requested changes
Precisa linkar a página no menu e linkar a página anterior a essa página.

2023-05-22 19:49 UTC, Mortaro commented
Thanks for the translation and sorry for the giant delay to merge this PR 💜

Links are now generated automatically and we can merge as is 🙏

2023-05-22 19:49 UTC, merged